version: '3'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: frontend
        env_file:
            - .env
        ports:
            - 3000:3000
